### ISSUE TITLE
<Bảng lương>Bổ sung xử lý thanh toán lương cho nhân viên

### ISSUE THREAD

**Issue by trieuconcrete** [trieuconcrete/laravel-admin#79]
## UI/UX
Button `Thanh toán`

<img width="1173" alt="Image" src="https://github.com/user-attachments/assets/ce4616fc-902f-4e39-abe5-cff87b978f61" />

## Xử lý 
```
Update: 
 - salary_details.status = paid
insert: transactions
 - type: expense
 - category: salary
 - ...
```
